name: Deploy new version
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '21'  # Specifying Node.js version 16

      - name: Build project
        run: npm run build

          #      - name: Upload production-ready build files
          #        uses: actions/upload-artifact@v2
          #        with:
          #          name: production-files
          #          path: ./dist

            #  deploy:
            #    name: Deploy
            #    needs: build
            #    runs-on: ubuntu-latest
            #    if: github.ref == 'refs/heads/main'
            #
            #    steps:
            #      - name: Download artifact
            #        uses: actions/download-artifact@v2
            #        with:
            #          name: production-files
            #          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Updated to v4 for potential improvements
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
